/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.0.6-44-g97bcda8388"
#endif /* AVUTIL_FFVERSION_H */
